/** Cursor Cloud Agent 환경 비밀 → 로컬 `.env.local` 재료. 값은 로그에 남기지 않는다. */

export const cloudAgentRequiredSecrets = [
  "DATABASE_URL",
  "NEON_AUTH_BASE_URL",
  "NEON_AUTH_COOKIE_SECRET",
  "CORELOOM_FOUNDER_EMAIL",
] as const;

/** 브라우저 로그인용. `.env.local`에 쓰지 않고 에이전트만 읽는다. */
export const cloudAgentLoginSecrets = [
  "TEST_LOGIN_USERNAME",
  "TEST_LOGIN_PASSWORD",
] as const;

export type CloudAgentRequiredSecret = (typeof cloudAgentRequiredSecrets)[number];
export type CloudAgentLoginSecret = (typeof cloudAgentLoginSecrets)[number];

export type CloudAgentEnvSource = Partial<
  Record<
    | CloudAgentRequiredSecret
    | CloudAgentLoginSecret
    | "CORELOOM_DATABASE_BRANCH"
    | "CORELOOM_DATABASE_HOST",
    string | undefined
  >
>;

export function missingCloudAgentSecrets(source: CloudAgentEnvSource) {
  return cloudAgentRequiredSecrets.filter((name) => !source[name]?.trim());
}

export function missingCloudAgentLoginSecrets(source: CloudAgentEnvSource) {
  return cloudAgentLoginSecrets.filter((name) => !source[name]?.trim());
}

function shellAssign(name: string, value: string) {
  return `${name}=${JSON.stringify(value.trim())}`;
}

/**
 * Cloud Agent용 `.env.local` 본문.
 * `TEST_LOGIN_*`는 파일에 넣지 않는다 — 로그인 시 환경 변수로만 쓴다.
 */
export function cloudAgentEnvironmentFile(source: CloudAgentEnvSource) {
  const missing = missingCloudAgentSecrets(source);
  if (missing.length > 0) {
    throw new Error(`Cloud Agent 비밀이 없습니다: ${missing.join(", ")}`);
  }

  const branch = source.CORELOOM_DATABASE_BRANCH?.trim() || "ai-development";
  // 확인된 접속 대상. 여기서 지어내지 않는다 — 없으면 마이그레이션이 스스로 멈춘다.
  const confirmedHost = source.CORELOOM_DATABASE_HOST?.trim();

  return [
    "# Generated by cloud-agent-bootstrap. Do not commit.",
    shellAssign("DATABASE_URL", source.DATABASE_URL!),
    shellAssign("CORELOOM_DATABASE_BRANCH", branch),
    ...(confirmedHost ? [shellAssign("CORELOOM_DATABASE_HOST", confirmedHost)] : []),
    shellAssign("NEON_AUTH_BASE_URL", source.NEON_AUTH_BASE_URL!),
    shellAssign("NEON_AUTH_COOKIE_SECRET", source.NEON_AUTH_COOKIE_SECRET!),
    shellAssign("CORELOOM_FOUNDER_EMAIL", source.CORELOOM_FOUNDER_EMAIL!),
    "",
  ].join("\n");
}
